name: ci

on:
  push:
    tags: [ 'v-*' ]

jobs:
  exec:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Exec
      run: bundle exec ruby ./app/main.rb
